# Generated by Django 6.0 on 2026-01-01 06:59

from django.db import migrations, models


def fix_null_is_blocked(apps, schema_editor):
    """Fix NULL values in is_blocked column for existing users"""
    try:
        with schema_editor.connection.cursor() as cursor:
            # Update NULL values to False
            cursor.execute(
                "UPDATE core_user SET is_blocked = FALSE WHERE is_blocked IS NULL"
            )
    except Exception:
        # Column might not exist yet, that's okay
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Add field (Django will handle if column already exists)
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, null=True),  # Allow null initially
        ),
        # Fix NULL values
        migrations.RunPython(fix_null_is_blocked, migrations.RunPython.noop),
        # Make it NOT NULL
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
