# Generated by Django 6.0 on 2025-12-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaint_feedback_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='city',
            field=models.CharField(default='Indore', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
