# Generated by Django 6.0 on 2025-12-30 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement_remove_user_dob_remove_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='rating',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Public Alert', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='General Issue', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ward_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Reopened', 'Reopened'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ticket_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
