# Generated by Django 6.0 on 2025-12-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_announcement_priority_remove_complaint_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ward_no',
        ),
    ]
