# Generated by Django 6.0 on 2025-12-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_ward_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='admin_remark',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='is_escalated',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='SOSAlert',
        ),
    ]
