# Generated by Django 6.0 on 2025-12-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_user_gender_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='rating',
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution',
            field=models.CharField(blank=True, choices=[('Fully Resolved', 'Fully Resolved'), ('Partially Resolved', 'Partially Resolved'), ('Not Resolved', 'Not Resolved')], max_length=20, null=True),
        ),
    ]
