# Generated by Django 6.0 on 2025-12-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_feedback_timestamps'),
    ]

    operations = [
    ]
