# Generated by Django 6.0 on 2025-12-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_complaint_fk'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_complai_752000_idx',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_time_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('complaint_filed', 'Complaint Filed'), ('status_update', 'Status Update'), ('assigned', 'Task Assigned'), ('feedback_needed', 'Feedback Needed'), ('escalation', 'Escalation Alert'), ('team_message', 'Team Message'), ('achievement', 'Achievement Unlocked')], max_length=50),
        ),
    ]
